### ISSUE TITLE
Yellow Star: Colonization

### ISSUE THREAD

**Issue by ropufu** [userXinos/HadesSpace#10]
https://userxinos.github.io/HadesSpace/yellowstar#colonize_prices

Colonization cost does not depend on the planet type, but rather on how many planets you have colonized. Say, if the 10th planet you colonize is an Ice planet, you can have it for just 200k.

**Comment by userXinos** [comment]
ah yes, it makes sense. Then leave it to make it easier to navigate, idk ?

**Comment by ropufu** [comment]
Not sure what you mean. It's your website, so you can do whatever you like with it :^) Just wanted to point out that that particular section is incorrect.
