### ISSUE TITLE
Maybe unify the '/compendiumTech' and '/modulesCalc' pages?

### ISSUE THREAD

**Issue by Serotonindude** [userXinos/HadesSpace#102]
Currently we have to enter our current level on both sites... But actually one could use the current levels entered on the modulesCalc site as input for the compendium bot and throw away the compendiumTech site all together... 
This would save maintenance work and increase useability and i could close one pinned tab in my browser :D

Anyway, thanks for the website! :)

**Comment by Serotonindude** [comment]
Oh, I see!
That button was not obvious enough. :D
And it's still not obvious what it does. There should be some text. 
So, why having /compendiumTech in the first place then?

**Comment by userXinos** [comment]
> So, why having /compendiumTech in the first place then?

Because this is a third-party integration... and the calculator has a synchronization function just as a feature

**Comment by Serotonindude** [comment]
Ah, ok then. :)
