### ISSUE TITLE
Weapon Amplifier lists damage reduction not aplification

### ISSUE THREAD

**Issue by stevecdavis** [userXinos/HadesSpace#32]
<html>
<body>

lvl | Unlock blueprints | Unlock price | Unlock Time | Damage reduction (PvE) | Damage reduction (PVP)
-- | -- | -- | -- | -- | --
1 | 1 000 | 1m | -20% | -20%
4 | 2 000 | 10m | -30% | -30%
15 | 3 000 | 1h | -40% | -40%

</body>
</html>

small snippet from the site. Believe it should be multiplication, am I wrong?

**Comment by userXinos** [comment]
It looks like that, can you send me a screenshot of the module how the values are formatted in the game ?

**Comment by stevecdavis** [comment]
Let me know if this works

**Comment by userXinos** [comment]
no need, I already received the screenshots
