### ISSUE TITLE
Incorrect Text Formatting and Translation Issues on German Language Switch

### ISSUE THREAD

**Issue by Vox314** [userXinos/HadesSpace#34]
## Description
On the webpage https://userxinos.github.io/HadesSpace/mining, when switching to the German language, the text does not format correctly. Words from one module spill over into another. Additionally, there are translation issues present.

## Steps to Reproduce
1. Navigate to https://userxinos.github.io/HadesSpace/mining
2. Switch the language to German.

## Expected Behavior
The text should format correctly with words contained within their respective modules. The translation should correctly display in German, and the page header should also translate to German.

## Actual Behavior
The text formatting is incorrect with words from one module appearing in another. "Modules miniers", which is a French translation, appears in the German translation. The page header does not translate and remains in English.

## Environment
- **Browser:** Opera and Microsoft Edge (tested only those!)
- **OS:** Windows 11 Pro

## Additional Information
Please see the attached screenshots for more context.\ 
Also I only randomly stumbled upon these issues; so this might also be the case on other pages of the site.

<img width="610" alt="image" src="https://github.com/userXinos/HadesSpace/assets/116598880/d7eec7c8-a13e-4b14-8864-7b81f2530492">
<img width="396" alt="image" src="https://github.com/userXinos/HadesSpace/assets/116598880/77eaabc0-9070-4849-91c0-a7b63bfcc4f3">
<img width="316" alt="image" src="https://github.com/userXinos/HadesSpace/assets/116598880/eddd4150-892b-4fbb-9830-f31a6f08ddb3">
<img width="276" alt="image" src="https://github.com/userXinos/HadesSpace/assets/116598880/16ba6668-9315-407a-a79d-bee552101489">
<img width="1253" alt="image" src="https://github.com/userXinos/HadesSpace/assets/116598880/d1c38f67-c59e-4a7b-8dec-43dfc8927fb0">

**Comment by userXinos** [comment]
Oh yes, support for other languages ​​other than English and Russian is extremely weak.  The screenshot was more than enough

**Comment by Vox314** [comment]
> Oh yes, support for other languages ​​other than English and Russian is extremely weak. Thank you for your detailed bug report, but the screenshot was more than enough.

Hahah, sorry; can't be too careful, also I suspect you just used google translate which actually did the job quite well but I was confused about why "Modules miniers" was french when having selected german. xD

**Comment by userXinos** [comment]
maybe it was my mistake. When I created the files I simply copied them and manually tried to keep all the localizations up to date for some time, yes, google translate

**Comment by userXinos** [comment]
I used GPTchat for translation, it seems it translated like in the game
