### ISSUE TITLE
[Feature] Option to sync module calculator with Compendium modules

### ISSUE THREAD

**Issue by texastoland** [userXinos/HadesSpace#63]
### Description

A toggle in the module calculator to use Compendium as the data source would be nice. Currently it needs updated in 2 places.

**Comment by texastoland** [comment]
Confirmed working! A little confusing when I click the button there's a select box with only 1 item called `new entry` (the default name). It'd be nice if the button worked automatically with only 1 entry.

**Comment by userXinos** [comment]
>worked automatically with only 1 entry. 

I’m not sure that this behavior will be expected for everyone

**Comment by texastoland** [comment]
Or possibly a clearer default name like `default profile` or something? Regardless thank you 🙌🏼

**Comment by texastoland** [comment]
PS I'm interested in adding graphs in the future. I'll find you on Discord when I'm ready!

**Comment by userXinos** [comment]
> Or possibly a clearer default name like default profile 
hmm, maybe
