### ISSUE TITLE
[Bug] Hades Space logo obscures menus at some resolutions

### ISSUE THREAD

**Issue by skellt** [userXinos/HadesSpace#70]
### Description

On my second monitor, which is an ancient 1280x1024 screen, I can't interact with the "Other" menu in the top menu bar because the Hades Space logo is above it. Any clicks there just go to the Hades Space home page because that's what clicking on the logo does. I can't widen the browser on that monitor any more. One workaround is to shrink the browser down to where the menu collapses into a hamburger menu and then use that. But then I have to maximize it again for best UX.

![hades-space-screen-width-issue](https://github.com/userXinos/HadesSpace/assets/12088251/2e0750ce-aada-4052-8a54-20dfb366b31d)

Some possible solutions:
1) The resolution at which the page changes layout could be adjusted so that it always shows the hamburger menu if the Hades Space logo would obscure any of the menus.
2) Hades Space logo could be all the way at the left before the menu items. Or it could be at the right near the gear icon. It would fit nicely at the right, but that's an odd place to have the link back to home page.

**Comment by userXinos** [comment]
forgot about this... this is because of the new HSC item, as a quick solution, I raised the minimum widht when switching to mobile mode
