### ISSUE TITLE
[Feature] -/+ buttons in the module calculator like in compendium

### ISSUE THREAD

**Issue by texastoland** [userXinos/HadesSpace#72]
### Description

![compendium](https://github.com/userXinos/HadesSpace/assets/48431/9e8d9d14-3212-477e-b635-d36484ce6fb0)
![modules calculator](https://github.com/userXinos/HadesSpace/assets/48431/474cff6a-d41f-4ff6-ab1d-2aa4a7b9d6ae)

**Comment by texastoland** [comment]
It's great! There may be a regression. Before only planned upgrades were shown in the calculator. Now all levels are shown even if the planned and current level are equal.

**Comment by userXinos** [comment]
Do you mean hide the planned one if it is equal to the actualy one ?

**Comment by texastoland** [comment]
Yes please 🙏🏼 I believe you already designed it like that previously.

**Comment by userXinos** [comment]
yes, this is not a complex feature, I just missed it when updating the component
