### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by 233dada** [userXinos/HadesSpace#98]
(if no any tips, then mean cd lost)
●TRADE
•Red star life extender
•Relic drone
•Dispatch (which additionally lost his preparation time)
●MINER
•Artifact boost
•Enrich (which lost its cd for RS)
•Hydrogen upload
●WEAPON
•Rocket launcher (which lost his min range for RS & YS and the MinEffectRadius hasn't been transformed)
●COMBAT
•Teleport (which lost its cd for BLS)
•Remote bomb (useless speed)
●DRONE
•the Rocket launcher of Rocket drone (useless unlock bp) https://userxinos.github.io/HadesSpace/drone#RocketDrone-modules-0
•the Chain ray of Chain ray turret (useless unlock bp) https://userxinos.github.io/HadesSpace/drone#ChainRayDrone-modules-0
•Turret of Laser turret (useless RS level) https://userxinos.github.io/HadesSpace/drone#LaserTurret-turret
•Delta drones (useless text "For battleship only", unlock bp and RS level for internal modules)
•Drone squad (many duplicates as above)
●SHIPS
•Weak battery of BS (useless RS level) https://userxinos.github.io/HadesSpace/ships#Battleship-modules-0
•Battery of flag ship (useless RS level) https://userxinos.github.io/HadesSpace/ships#Battery
•Immolation
•Recoil (which additionally lost active delay)
•Stealth (useless unlock bp)
•Recoil drones (which lost its lifetime)
•Battery of drone (useless RS level) https://userxinos.github.io/HadesSpace/ships#FlagshipDroneSwarm-modules-0
•EMP rocket
•Cataclysm
•Floating shield (which lost its lifetime)
•Dart turret (which lost its lifetime)
●YS
•YS Cerberus spawn (colossus exchanged with guardian)
●RS
•sector cooldown after enrich/genesis 
•text "HydroCostModifierPct" (which hasn't been transformed)
•text "ArtifactDRSPoints" (which hasn't been transformed)
●WS
•sector cooldown after enrich/genesis (which are 0)
•Max waypoints (which lost)
●CERBERUS
•Weak battery (a duplicate) https://userxinos.github.io/HadesSpace/cerberus#CerberusGuardian-modules-0
•Mass battery of interceptor (useless RS level) https://userxinos.github.io/HadesSpace/cerberus#CerberusInterceptor-modules-0
•Laser of colossus (useless RS level) https://userxinos.github.io/HadesSpace/cerberus#CerberusColossus-modules-0
•Salvage (which lost its heal amount. And useless RS level) https://userxinos.github.io/HadesSpace/cerberus#CerberusColossus-modules-0
•Destroyer vengeance (useless RS level) https://userxinos.github.io/HadesSpace/cerberus#CerberusDestroyer-modules-0
•Bomber rocket (useless RS level. And the text "NumProjectiles" hasn't been transformed) https://userxinos.github.io/HadesSpace/cerberus#CerberusBomber-modules-0
•Ally shield of phoenix (useless RS level) https://userxinos.github.io/HadesSpace/cerberus#CerberusPhoenix-modules-0
•Dart barrage (useless RS level)
•Hydra barrage (useless RS level)
•Cerberus carrier (the text "PeriodSpawnType" & "AITeleportDelay" haven't been transformed)
•duplicate to dark version
●SPACE STATION
•text "SeparateBuildingPerLevel" (which I think is useless)
•text "PrefabModel_WithStarHarvester" (which I think is useless)
•text "StarScannerType" (which is useless)

**Comment by userXinos** [comment]
Thank you for all your hard work. Some points were deliberately ignored:

Delta drones (useless text "For battleship only") - why ?

Battery of flag ship (useless RS level) - this is literally a link to the original module, hiding the lines will affect the player module

Battery of drone (useless RS level) - player module

sector cooldown after enrich/genesis (which are 0) - let it be for now, maybe it's temporary, idk

Weak battery (a duplicate) - ???

Cerberus carrier (the text "PeriodSpawnType" & "AITeleportDelay" haven't been transformed) - I don’t know what it is at all, it looks like this ship is still in development

**Comment by 233dada** [comment]
> Thank you for all your hard work. Some points were deliberately ignored:
> 
> Delta drones (useless text "For battleship only") - why ?
> 
> Battery of flag ship (useless RS level) - this is literally a (hard)link to the original module, hiding the lines will affect the player module
> 
> Battery of drone (useless RS level) - player module
> 
> sector cooldown after enrich/genesis (which are 0) - let it be for now, maybe it's temporary, idk
> 
> Weak battery (a duplicate) - ???
> 
> Cerberus carrier (the text "PeriodSpawnType" & "AITeleportDelay" haven't been transformed) - I don’t know what it is at all, it looks like this ship is still in development

Thanks for your reply

In my opinion, Delta Drones is a drone module which only belongs to battleships, and which was called Recoil Drones on the Flagships

Weak battery (a duplicate) - ??? - It was mentioned at SHIPS part

That's all
